[project]
name = "week_1_project"
version = "0.1.0"
description = "Flask REST API for managing student records."
authors = [
    { name = "Nassih chaimae", email = "nassihchaimae30@gmail.com" }
]
dependencies = [
    "Flask==3.1.2",
    "python-dotenv==1.1.1",
]